const validateColor = (color) => {
    const colors = [
        `AliceBlue`,
        `AntiqueWhite`,
        `Aqua`,
        `Aquamarine`,
        `Azure`,
        `Beige`,
        `Bisque`,
        `Black`,
        `BlanchedAlmond`,
        `Blue`,
        `BlueViolet`,
        `Brown`,
        `BurlyWood`,
        `CadetBlue`,
        `Chartreuse`,
        `Chocolate`,
        `Coral`,
        `CornflowerBlue`,
        `Cornsilk`,
        `Crimson`,
        `Cyan`,
        `DarkBlue`,
        `DarkCyan`,
        `DarkGoldenRod`,
        `DarkGray`,
        `DarkGrey`,
        `DarkGreen`,
        `DarkKhaki`,
        `DarkMagenta`,
        `DarkOliveGreen`,
        `DarkOrange`,
        `DarkOrchid`,
        `DarkRed`,
        `DarkSalmon`,
        `DarkSeaGreen`,
        `DarkSlateBlue`,
        `DarkSlateGray`,
        `DarkSlateGrey`,
        `DarkTurquoise`,
        `DarkViolet`,
        `DeepPink`,
        `DeepSkyBlue`,
        `DimGray`,
        `DimGrey`,
        `DodgerBlue`,
        `FireBrick`,
        `FloralWhite`,
        `ForestGreen`,
        `Fuchsia`,
        `Gainsboro`,
        `GhostWhite`,
        `Gold`,
        `GoldenRod`,
        `Gray`,
        `Grey`,
        `Green`,
        `GreenYellow`,
        `HoneyDew`,
        `HotPink`,
        `IndianRed`,
        `Indigo`,
        `Ivory`,
        `Khaki`,
        `Lavender`,
        `LavenderBlush`,
        `LawnGreen`,
        `LemonChiffon`,
        `LightBlue`,
        `LightCoral`,
        `LightCyan`,
        `LightGoldenRodYellow`,
        `LightGray`,
        `LightGrey`,
        `LightGreen`,
        `LightPink`,
        `LightSalmon`,
        `LightSeaGreen`,
        `LightSkyBlue`,
        `LightSlateGray`,
        `LightSlateGrey`,
        `LightSteelBlue`,
        `LightYellow`,
        `Lime`,
        `LimeGreen`,
        `Linen`,
        `Magenta`,
        `Maroon`,
        `MediumAquaMarine`,
        `MediumBlue`,
        `MediumOrchid`,
        `MediumPurple`,
        `MediumSeaGreen`,
        `MediumSlateBlue`,
        `MediumSpringGreen`,
        `MediumTurquoise`,
        `MediumVioletRed`,
        `MidnightBlue`,
        `MintCream`,
        `MistyRose`,
        `Moccasin`,
        `NavajoWhite`,
        `Navy`,
        `OldLace`,
        `Olive`,
        `OliveDrab`,
        `Orange`,
        `OrangeRed`,
        `Orchid`,
        `PaleGoldenRod`,
        `PaleGreen`,
        `PaleTurquoise`,
        `PaleVioletRed`,
        `PapayaWhip`,
        `PeachPuff`,
        `Peru`,
        `Pink`,
        `Plum`,
        `PowderBlue`,
        `Purple`,
        `RebeccaPurple`,
        `Red`,
        `RosyBrown`,
        `RoyalBlue`,
        `SaddleBrown`,
        `Salmon`,
        `SandyBrown`,
        `SeaGreen`,
        `SeaShell`,
        `Sienna`,
        `Silver`,
        `SkyBlue`,
        `SlateBlue`,
        `SlateGray`,
        `SlateGrey`,
        `Snow`,
        `SpringGreen`,
        `SteelBlue`,
        `Tan`,
        `Teal`,
        `Thistle`,
        `Tomato`,
        `Turquoise`,
        `Violet`,
        `Wheat`,
        `White`,
        `WhiteSmoke`,
        `Yellow`,
        `YellowGreen`,
    ]
    const confirmColor = color.split('')
    const hexcode = new RegExp("^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$")
    if (confirmColor[0] != '#') {
        for (let i=0; i < colors.length; i++) {
            const userColor = color.toLowerCase()
            
            if (userColor === colors[i].toLowerCase()) {
                // console.log(color.toLowerCase())
                // console.log(colors[i].toLowerCase())
                return color
            } else {
                // return (`your color is : ${color}`)
            }
        }
    } else if (hexcode.test(color)) {
        return color
    }
}

module.exports = { validateColor }